version: '3'

volumes:
  mysql_data:
    driver: local

networks:
  backend:
  frontend:

services:
  proxy:
    build: .
    depends_on:
      - keycloak_prod-container
      - brainfree-backend-container
      - brainfree-frontend-container
    ports:
      - "80:80"
      - "443:443"
    container_name: proxy
    hostname: proxy
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - backend
      - frontend

  keycloak_prod-container:
    image: jboss/keycloak:16.1.1
    env_file: keycloak.env
    hostname: keycloak_prod
    ports:
      - "8080:8080"
    volumes:
      - ../keycloak/imports:/opt/jboss/keycloak/imports
    restart: on-failure
    networks:
      - backend
      - frontend
    depends_on:
      - keycloak_prod_db

  keycloak_prod_db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    env_file: keycloak.env
    restart: on-failure
    networks:
      - backend

  brainfree-backend-container:
    image: docker.pkg.github.com/fi-ml/brainfree-webapp-backend/backend:sha-362c993
    container_name: brainfree-prod-server
    env_file: brainfree.env
    volumes:
      - ./sql/create_productTable.sql:/docker-entrypoint-initdb.d/create_product_table.sql
      - ./sql/insert_products.sql:/docker-entrypoint-initdb.d/insert_products.sql
    hostname: brainfree_backend
    networks:
      - backend
      - frontend
    depends_on:
      - brainfree-prod-db
    restart: on-failure

  brainfree-frontend-container:
    image: docker.pkg.github.com/fi-ml/brainfree_webapp_ui/frontend:sha-a74b5f1
    container_name: brainfree-frontend-server
    ports:
      - "8081:80"
    networks:
      - frontend

  brainfree-prod-db:
    image: 'kartoza/postgis:13-3.1'
    container_name: brainfree-prod-db
    env_file: postgres.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - frontend


  portainer:
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    image: portainer/portainer-ce
    hostname: portainer
    container_name: portainer
    networks:
      - backend
