FROM nginx:stable

#  default conf for proxy service
COPY proxy.conf /etc/nginx/conf.d/proxy.conf


#  Proxy and SSL configurations
#COPY includes/ /etc/nginx/includes/

# Proxy SSL certificates
#COPY ./ssl/ /etc/ssl/certs/nginx/
