name: brainfree pipeline

on:
  push:
    branches: [ main ]
jobs:
  brainfree-webapp-ui:
    runs-on: ubuntu-latest
    steps:
      - name: brainfree webapp frontend
        uses: actions/checkout@v3.1.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_AUTH_TOKEN  }}
          repository: fi-ml/brainfree-webapp/tree/master/brainfree_ui
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push:   ${{ github.event_name != 'pull_request' }}
          tags:   ${{ github.repository_owner }}/app:latest
          labels: ${{ steps.meta.outputs.labels }}
